"""empty message

Revision ID: 23e3bd39850d
Revises: 65cb8e606868
Create Date: 2022-06-11 19:07:42.020816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e3bd39850d'
down_revision = '65cb8e606868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
