"""empty message

Revision ID: 403b53ccdc39
Revises: 
Create Date: 2022-05-23 13:00:38.367250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403b53ccdc39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('update people set completed=false where completed is null')
    # ### end Alembic commands ###
    op.alter_column('people','completed',nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'completed')
    # ### end Alembic commands ###
